feat(ci): add artifact upload
noctisynth/Quantumix pull request #3
Opened 2023-12-24 18:23 UTC by HsiangNianian

2023-12-24 19:23 UTC, HsiangNianian commented
你需要将 `${{ secrets.USERNAME_PASSWORD }}` 填写为 `username:password` 的形式存储在secrets里，这样才能让 Windows 镜像的 ci 中的 git 完成登录验证

2023-12-25 02:07 UTC, fu050409 commented
你是指账号密码？现在的GitHub似乎已经不支持密码验证。

2023-12-25 03:55 UTC, HsiangNianian commented
> 你是指账号密码？现在的GitHub似乎已经不支持密码验证。

你也可以添加 ssh

2023-12-25 05:58 UTC, fu050409 commented
这个目前看起来submodule的认证还没有解决

2023-12-25 06:00 UTC, fu050409 commented
除此之外，我在 #6 里面提到的，pr目前还是不能正常走Workflow，需要check一下

2023-12-25 06:06 UTC, fu050409 requested changes
oblivion的路径不能修改，改submodule吧，这样会破坏其他contributor的环境

2023-12-25 12:45 UTC, fu050409 approved these changes

2023-12-25 12:46 UTC, merged